---
- name: web_1_inspect
  shell: "docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' web_1"
  register: ip1
- set_fact:
    web_ip_1: "{{ ip1.stdout }}"

- name: web_2_inspect
  shell: "docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' web_2"
  register: ip2
- set_fact:
    web_ip_2: "{{ ip2.stdout }}"

- name: web_3_inspect
  shell: "docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' web_3"
  register: ip3
- set_fact:
    web_ip_3: "{{ ip3.stdout }}"

- name: nginx.conf
  become: true
  template:
    src: nginx.conf.j2
    dest: /home/ansible/nginx.conf

- name: nginx_cont
  docker_container:
    name: nginx
    hostname: nginx
    state: started
    image: "nginx"
    pull: true
    ports:
      - "8085:80"    
    networks:
      - name: project
    volumes:
      - /home/ansible/nginx.conf:/etc/nginx/nginx.conf:ro
